name: Auto Commit

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Roda a cada 6 horas

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Auto Commit
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto commit"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
